Ignore position error smaller than the resolution
sbgisen/vesc pull request #89
Opened 2023-08-02 06:02 UTC by Tacha-S

## Change Summary

Subscribe `~limit` topic, and duty set to 0 when the servo reached to limit.

- fix #88 

## Details

## Impacts

## References

## Additional Information

2023-08-07 10:55 UTC, nyxrobotics requested changes

2023-08-07 10:55 UTC, nyxrobotics commented on vesc_hw_interface/src/vesc_servo_controller.cpp
> +  auto rate = std::accumulate(limit_deque_.begin(), limit_deque_.end(), 0.0) / limit_deque_.size();
平均という意味であれば`rate`->`average`が良いと思います

2023-08-07 10:55 UTC, nyxrobotics commented on vesc_hw_interface/src/vesc_servo_controller.cpp
> +void VescServoController::limit(const std_msgs::Bool::ConstPtr& msg)
`VescServoController::endstopCallback`等が良いように思います

2023-08-07 10:55 UTC, nyxrobotics commented on vesc_hw_interface/src/vesc_servo_controller.cpp
> +  nh.param<bool>("servo/use_limit_sensor", use_limit, false);
`servo/use_endstop`が良いと思います

2023-08-07 10:55 UTC, nyxrobotics commented on vesc_hw_interface/src/vesc_servo_controller.cpp
> +    limit_sub_ = nh.subscribe("limit", 1, &VescServoController::limit, this);
`limit`より`endstop`の方が機能がわかりやすいように思います

2023-08-07 10:55 UTC, nyxrobotics commented on vesc_hw_interface/src/vesc_servo_controller.cpp
> +  nh.param<double>("servo/calibration_strict_current", calibration_strict_current_, calibration_current_);
`calibration_strict_current` == `servo/calibration_current` のときは二回目のキャリブレーション動作に移行せず一回目で終わるようにして頂いてるのですが、それがぱっと見でわかりにくいので`servo/calibration_strict_current`と`servo/calibration_strict_duty`の説明と併せてREAMDEに追記いただいたほうが良いと思います

2023-08-07 10:55 UTC, nyxrobotics commented on vesc_hw_interface/src/vesc_servo_controller.cpp
> +  nh.param<double>("servo/limit_margin", limit_margin_, 0.02);
`limit_margin_`はどういう機能でしょう、発振防止でしょうか？

2023-08-08 00:04 UTC, Tacha-S commented on vesc_hw_interface/src/vesc_servo_controller.cpp
> +  nh.param<double>("servo/limit_margin", limit_margin_, 0.02);
The `target_position` is continuously provided by the ros_controller. If the current position is not reset once the `target_position` gets sufficiently close to the `endpoint`, a significant position error will occur, leading to abrupt acceleration. On the other hand, there's no guarantee that the difference between `target_position` and the `endpoint` will always approach machine epsilon. Therefore, we've parameterized the threshold for determining how much error is acceptable before considering it to have converged.

2023-08-08 08:55 UTC, nyxrobotics commented on vesc_hw_interface/launch/position_control_sample.launch
> +        limit_margin: 0.02
limit->endstop

2023-08-09 02:55 UTC, nyxrobotics approved these changes

2023-08-09 03:02 UTC, merged