Fix position controller bugs
sbgisen/vesc pull request #97
Opened 2024-09-18 06:19 UTC by Tacha-S

## Change Summary

- Execute calibration on configure.
- Wait for controller's command.
- Do not accept a command over the limits.
- Load `joint_type` and `position limit` from URDF.

## Details

## Impacts

## References

## Additional Information

2024-09-19 09:46 UTC, Tacha-S commented
The issue with jerky motion due to control cycle problems still remains, but it's functioning for now.

2024-11-01 08:48 UTC, jsupratman13 requested changes

2024-11-01 08:48 UTC, jsupratman13 commented on vesc_hw_interface/README.md
>  - `torque_const` (double, *default*: 1.0): motor torque constant (unit: Nm/A).
`robot_description_name`もいらないと思う

2024-11-01 08:48 UTC, jsupratman13 commented on vesc_hw_interface/src/vesc_hw_interface.cpp
>      }
おそらく joint limitを取りたよね？
info_.limitsを使った方がいい、hardware interface側で joint limitと ros2_control jointリミットを比較して一番きついリミットをとるから

2024-11-01 09:20 UTC, jsupratman13 approved these changes

2024-11-01 09:20 UTC, merged